# Generated by Django 5.2.3 on 2025-07-05 11:18

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedYearlyStats',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodhubModel',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('apple_pay', models.CharField(max_length=255)),
                ('card_payment', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('cuisines', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField()),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('new_takeaway', models.CharField(max_length=255)),
                ('payment_provider', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('preorder', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('shop_id_company', models.CharField(max_length=255)),
                ('shop_name', models.CharField(max_length=255)),
                ('shop_url_company', models.CharField(max_length=255)),
                ('store_status_collection', models.CharField(max_length=255)),
                ('store_status_delivery', models.CharField(max_length=255)),
                ('store_status_restaurant', models.CharField(max_length=255)),
                ('total_reviews', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'foodhub',
            },
        ),
    ]
