# Generated by Django 5.2.3 on 2025-07-05 11:18

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JustEat',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('last_update', models.DateTimeField()),
                ('shop_id_company', models.CharField(max_length=20, unique=True)),
                ('shop_url_company', models.CharField(max_length=200)),
                ('shop_name', models.CharField(max_length=255)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.CharField(blank=True, max_length=100, null=True)),
                ('total_reviews', models.CharField(blank=True, max_length=100, null=True)),
                ('cuisines', models.CharField(blank=True, max_length=255, null=True)),
                ('openingTimeLocal', models.DateTimeField(blank=True, null=True)),
                ('deliveryOpeningTimeLocal', models.DateTimeField(blank=True, null=True)),
                ('isCollection', models.CharField(max_length=255)),
                ('isDelivery', models.CharField(max_length=255)),
                ('isOpenNowForCollection', models.CharField(max_length=255)),
                ('isOpenNowForDelivery', models.CharField(max_length=255)),
                ('isOpenNowForPreorder', models.CharField(max_length=255)),
                ('isTemporarilyOffline', models.CharField(max_length=255)),
                ('isTemporaryBoost', models.CharField(max_length=255)),
                ('isPremier', models.CharField(max_length=255)),
                ('isNew', models.CharField(max_length=255)),
                ('isTestRestaurant', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'justeat',
            },
        ),
    ]
